apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone-pr.yaml
  creationTimestamp: null
  name: preview
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          volumeMounts:
          - mountPath: /home/jenkins
            name: workspace-volume
          - mountPath: /etc/podinfo
            name: podinfo
            readOnly: true
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/jx-cli:latest
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env bash
            set -x
            jx gitops variables
            export BUILD_NUMBER=$BUILD_NUMBER-1
        - image: gcr.io/jenkinsxio/jx-cli:latest
          name: env
          resources: {}
          script: |
            #!/usr/bin/env bash
            set -x
            env | sort
            cat /workspace/source/.jx/variables.sh
        - image: gcr.io/jenkinsxio/jx-cli:latest
          name: ls
          resources: {}
          script: |
            #!/usr/bin/env bash
            set -x
            ls /workspace
            ls /workspace/source
        - image: gcr.io/jenkinsxio/jx-cli:latest
          name: promote-jx-preview
          resources: {}
          script: |
            #!/bin/bash
            set -x
            env | sort
            source /workspace/source/.jx/variables.sh
            jx preview create
        volumes:
        - emptyDir: {}
          name: workspace-volume
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
